### ISSUE TITLE
Unable to load module

### ISSUE THREAD

**Issue by federicovezzoli** [0beqz/screen-space-reflections#9] opened 2022-07-18 09:32 UTC
With three in the latest version (0.142.0) if I try to use `@react-three/postprocessing` I get an error:

` Error: Cannot find module '/xxx/node_modules/three/examples/jsm/capabilities/WebGL'`

Which I could track back to this package, it seems that your require statement isn't valid anymore.

Is there a way to fix this?
thanks

**Comment by 0beqz** [comment] 2022-07-18 16:15
Yeah this effect needs that "WebGL.js" module from three.js' demo folder to check if WebGL2 is available. I just inlined that function now and removed the import of the "WebGL.js".
Could you test if the issue is resolved in the newest version (2.0.3)?

**Closed** 2022-07-19 22:32 UTC
